In [7]:
import numpy as np

In [8]:
data = []
with open("data/day4.txt", "r") as input:
    for l in input:
        newline = l.rstrip()
        line_contents = newline.split()
        data.append(line_contents)

In [9]:
# Take out the bingo calls
calls = data[0][0].split(sep = ",")
calls = list(map(int, calls))

In [10]:
# Build the bingo boards
boards_raw = data[2:]
board_set = []
board_count = 0
while board_count < len(boards_raw):
    for i in range(board_count, board_count +5):
        int_them = list(map(int, boards_raw[i]))
        board_set.append(int_them)
    board_count +=6

In [11]:
# Make them numpy arrays
board_arrays = []
board_count = 0
for board in board_set:
    board_arrays.append(np.array(board_set[board_count:board_count +5]))
    board_count +=5

In [12]:
for call in calls:
    for index, board in enumerate(board_arrays):
        for row in board:
            for i in range(len(row)):
                if row[i] == call:
                    row[i] = 0
                    if (sum(row) == 0) or (sum(board[:,i]) == 0):
                        winning_board = board
                        winning_sum = board.sum()
                        last_call = call
                        print("WINNER, BOARD",index, board)
                        print("Last call:",last_call)
                        print("Winning sum:",winning_sum)
                        print("Winning score:", winning_sum * last_call)
                        break
                    else:
                        continue
                    break
                else:
                    continue
                break
            else:
                continue
            break
        else:
            continue
        break
    else:
        continue
    break

WINNER, BOARD 15 [[ 0  5 38 41 95]
 [70  0 11 21 51]
 [81 20  0 14 83]
 [57 36 60 59 42]
 [ 0  0  0  0  0]]
Last call: 77
Winning sum: 784
Winning score: 60368
